(function(g){var window=this;var bqa=function(a,b){return g.Vb(a,b)},c5=function(a,b,c){a.l.set(b,c)},d5=function(a){c5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},e5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.Um(a.l,b,c)},cqa=function(a,b){var c=[];
g.Yi(b,function(d){try{var e=g.Zn.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.Yn(e)&&c.push(d):c.push(d)},a);
return c},dqa=function(a,b){var c=cqa(a,b);
(0,g.z)(c,function(d){g.Zn.prototype.remove.call(this,d)},a)},f5=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},eqa=function(a,b){g.ab(a,b)||a.push(b)},g5=function(a){var b=0,c;
for(c in a)b++;return b},h5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},i5=function(){},fqa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gqa=function(a){if(a.Ec&&"function"==typeof a.Ec)return a.Ec();
if(g.u(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},hqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.u(a))(0,g.z)(a,b,void 0);else{if(a.Pd&&"function"==typeof a.Pd)var c=a.Pd();else if(a.Ec&&"function"==typeof a.Ec)c=void 0;else if(g.La(a)||g.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=gqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},iqa=function(a,b,c,d){var e=new g.Im(null,void 0);
a&&g.Jm(e,a);b&&g.Km(e,b);c&&g.Lm(e,c);d&&(e.i=d);return e},j5=function(a,b){g.bp[a]=!0;
var c=g.$o();c&&c.publish.apply(c,arguments);g.bp[a]=!1},k5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Fm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jqa(this,a.capabilities||""),kqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},jqa=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.Qa(bqa,lqa)).forEach(function(c){a.capabilities.add(c)})},kqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},l5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},m5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},n5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},mqa=function(a){return new l5(a)},o5=function(a){return g.Ka(a)?(0,g.B)(a,mqa):[]},p5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},q5=function(a){return g.Ka(a)?"["+(0,g.B)(a,p5).join(",")+"]":"null"},r5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},nqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},s5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},t5=function(a,b){return g.Ya(a,function(c){return m5(c,b)})},u5=function(a){try{var b=(0,g.As)(),c=(0,g.zs)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},oqa=function(){var a=(0,g.zs)();
a&&dqa(a,a.g.nf(!0))},v5=function(){var a=g.Cs("yt-remote-connected-devices")||[];
g.qb(a);return a},pqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},w5=function(a){g.Bs("yt-remote-connected-devices",a,86400)},y5=function(){if(x5)return x5;
var a=g.Cs("yt-remote-device-id");a||(a=r5(),g.Bs("yt-remote-device-id",a,31536E3));for(var b=v5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return x5=d},z5=function(){var a=v5(),b=y5();
g.ab(a,b);g.Ds()&&g.sb(a,b);a=pqa(a);if(0==a.length)try{g.yr("remote_sid")}catch(c){}else try{g.xr("remote_sid",a.join(","),-1)}catch(c){}},A5=function(){return g.Cs("yt-remote-session-browser-channel")},B5=function(){return g.Cs("yt-remote-local-screens")||[]},C5=function(){g.Bs("yt-remote-lounge-token-expiration",!0,86400)},qqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(B5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.eh)(c,function(d){return!g.ab(b,d)})&&C5();
g.Bs("yt-remote-local-screens",a,31536E3)},rqa=function(a,b){g.Bs("yt-remote-session-browser-channel",a);
g.Bs("yt-remote-session-screen-id",b);var c=v5(),d=y5();g.ab(c,d)||c.push(d);w5(c);z5()},D5=function(a){a||(u5("yt-remote-session-screen-id"),u5("yt-remote-session-video-id"));
z5();a=v5();g.db(a,y5());w5(a)},F5=function(){if(!E5){var a=g.jo();
a&&(E5=new g.Tn(a))}return E5?!!E5.get("yt-remote-use-staging-server"):!1},G5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},H5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},J5=function(a){a.length?I5(a.shift(),function(){J5(a)}):K5()},sqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},I5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},K5=function(){var a=H5();
a&&a(!1,"No cast extension found")},L5=function(){if(tqa){var a=2,b=H5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;I5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",K5,c)}},uqa=function(){L5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);J5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},M5=function(a,b,c){g.H.call(this);
this.B=null!=c?(0,g.y)(a,c):a;this.Xc=b;this.A=(0,g.y)(this.oD,this);this.g=!1;this.i=0;this.l=this.Ca=null;this.o=[]},N5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return fqa(a)},O5=function(){},P5=function(){},Q5=function(){},S5=function(a){return(a=R5(a))?new ActiveXObject(a):new XMLHttpRequest},R5=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},T5=function(a,b,c,d){this.g=a;
this.l=b;this.D=c;this.B=d||1;this.o=45E3;this.ca=new g.aY(this);this.i=new g.al;this.i.setInterval(250)},V5=function(a,b,c){a.Xh=1;
a.Xf=d5(b.clone());a.ph=c;a.A=!0;U5(a,null)},W5=function(a,b,c,d,e){a.Xh=1;
a.Xf=d5(b.clone());a.ph=null;a.A=c;e&&(a.hA=!1);U5(a,d)},U5=function(a,b){a.Ci=(0,g.D)();
X5(a);a.Bg=a.Xf.clone();e5(a.Bg,"t",a.B);a.al=0;a.sc=a.g.Fp(a.g.Nk()?b:null);0<a.mq&&(a.Un=new g.dl((0,g.y)(a.hB,a,a.sc),a.mq));a.ca.ea(a.sc,"readystatechange",a.fM);var c=a.Xg?g.cc(a.Xg):{};a.ph?(a.Do="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Bg,a.Do,a.ph,c)):(a.Do="GET",a.hA&&!g.Ld&&(c.Connection="close"),a.sc.send(a.Bg,a.Do,null,c));a.g.ze(1)},d6=function(a,b,c){for(var d=!0;!a.Mg&&a.al<c.length;){var e=vqa(a,c);
if(e==Y5){4==b&&(a.og=4,Z5(15),d=!1);break}else if(e==$5){a.og=4;Z5(16);d=!1;break}else a6(a,e)}4==b&&0==c.length&&(a.og=1,Z5(17),d=!1);a.Ae=a.Ae&&d;d||(b6(a),c6(a))},vqa=function(a,b){var c=a.al,d=b.indexOf("\n",c);
if(-1==d)return Y5;c=Number(b.substring(c,d));if(isNaN(c))return $5;d+=1;if(d+c>b.length)return Y5;var e=b.substr(d,c);a.al=d+c;return e},g6=function(a,b){a.Ci=(0,g.D)();
X5(a);var c=b?window.location.hostname:"";a.Bg=a.Xf.clone();c5(a.Bg,"DOMAIN",c);c5(a.Bg,"t",a.B);try{a.Ee=new ActiveXObject("htmlfile")}catch(n){b6(a);a.og=7;Z5(22);c6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in e6)k=e6[l];else if(l in f6)k=e6[l]=f6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
e6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.rc("b/12014412"),d+"</body></html>");a.Ee.open();a.Ee.write(g.Mc(c));a.Ee.close();a.Ee.parentWindow.m=(0,g.y)(a.vL,a);a.Ee.parentWindow.d=(0,g.y)(a.pz,a,!0);a.Ee.parentWindow.rpcClose=(0,g.y)(a.pz,a,!1);c=a.Ee.createElement("DIV");a.Ee.parentWindow.document.body.appendChild(c);d=g.Cc(a.Bg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.ze(1)},X5=function(a){a.mt=(0,g.D)()+a.o;
h6(a,a.o)},h6=function(a,b){if(null!=a.Si)throw Error("WatchDog timer not null");
a.Si=i6((0,g.y)(a.FL,a),b)},j6=function(a){a.Si&&(g.w.clearTimeout(a.Si),a.Si=null)},c6=function(a){a.g.mw()||a.Mg||a.g.In(a)},b6=function(a){j6(a);
g.Bi(a.Un);a.Un=null;a.i.stop();g.cY(a.ca);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.Ee&&(a.Ee=null)},a6=function(a,b){try{a.g.jz(a,b),a.g.ze(4)}catch(c){}},l6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;k6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){l6(a,b,c,d,f)},f)})}},k6=function(a,b,c){var d=new Image;
d.onload=function(){try{m6(d),c(!0)}catch(e){}};
d.onerror=function(){try{m6(d),c(!1)}catch(e){}};
d.onabort=function(){try{m6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{m6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
h5(d,a)},m6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},n6=function(a){this.g=a;
this.i=new O5},p6=function(a){var b=o6(a.g,a.ej,"/mail/images/cleardot.gif");
d5(b);l6(b.toString(),5E3,(0,g.y)(a.vC,a),3,2E3);a.ze(1)},r6=function(a){var b=a.g.G;
if(null!=b)Z5(5),b?(Z5(11),q6(a.g,a,!1)):(Z5(12),q6(a.g,a,!0));else if(a.Gd=new T5(a,void 0,void 0,void 0),a.Gd.Xg=a.kq,b=a.g,b=o6(b,b.Nk()?a.Jj:null,a.lq),Z5(5),!g.Jd||g.ld(10))e5(b,"TYPE","xmlhttp"),W5(a.Gd,b,!1,a.Jj,!1);else{e5(b,"TYPE","html");var c=a.Gd;a=!!a.Jj;c.Xh=3;c.Xf=d5(b.clone());g6(c,a)}},s6=function(a){g.qk.call(this);
this.headers=new g.Fm;this.N=a||null;this.i=!1;this.T=this.g=null;this.Z=this.F="";this.A=0;this.l="";this.o=this.aa=this.D=this.R=!1;this.B=0;this.G=null;this.X="";this.J=this.S=!1},wqa=function(a){return g.Jd&&g.kd(9)&&g.Fa(a.timeout)&&g.Da(a.ontimeout)},xqa=function(a){return"content-type"==a.toLowerCase()},v6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.A=5;t6(a);u6(a)},t6=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},y6=function(a){if(a.i&&"undefined"!=typeof g.gY)if(a.T[1]&&4==w6(a)&&2==a.getStatus())x6(a,"Local request error detected and ignored");
else if(a.D&&4==w6(a))g.bl(a.ow,0,a);else if(a.dispatchEvent("readystatechange"),4==w6(a)){x6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.tf(1,String(a.F));if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!yqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<w6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";t6(a)}}finally{u6(a)}}},u6=function(a,b){if(a.g){z6(a);
var c=a.g,d=a.T[0]?g.Ha:null;a.g=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},z6=function(a){a.g&&a.J&&(a.g.ontimeout=null);
a.G&&(g.w.clearTimeout(a.G),a.G=null)},w6=function(a){return a.g?a.g.readyState:0},A6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},x6=function(a,b){return b+" ["+a.Z+" "+a.F+" "+a.getStatus()+"]"},B6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.A=new O5;this.F=a||null;this.G=null!=b?b:null;this.B=c||!1},zqa=function(a,b){this.g=a;
this.map=b;this.context=null},C6=function(a){g.Sj.call(this,"statevent",a)},D6=function(a,b){g.Sj.call(this,"timingevent",a);
this.size=b},E6=function(a){g.Sj.call(this,"serverreachability",a)},I6=function(a){F6(a);
if(3==a.g){var b=a.rk++,c=a.gm.clone();c5(c,"SID",a.l);c5(c,"RID",b);c5(c,"TYPE","terminate");G6(a,c);b=new T5(a,a.l,b,void 0);b.Xh=2;b.Xf=d5(c.clone());h5(new Image,b.Xf.toString());b.Ci=(0,g.D)();X5(b)}H6(a)},K6=function(a){a.NC(1,0);
a.gm=o6(a,null,a.jq);J6(a)},F6=function(a){a.eg&&(a.eg.abort(),a.eg=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.qf&&(g.w.clearTimeout(a.qf),a.qf=null);L6(a);a.Cd&&(a.Cd.cancel(),a.Cd=null);a.mg&&(g.w.clearTimeout(a.mg),a.mg=null)},M6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new zqa(a.JH++,b));2!=a.g&&3!=a.g||J6(a)},J6=function(a){a.Cd||a.mg||(a.mg=i6((0,g.y)(a.oz,a),0),a.Qh=0)},P6=function(a,b){if(1==a.g){if(!b){a.rk=Math.floor(1E5*Math.random());
var c=a.rk++,d=new T5(a,"",c,void 0);d.Xg=null;var e=N6(a),f=a.gm.clone();c5(f,"RID",c);c5(f,"CVER","1");G6(a,f);V5(d,f,e);a.Cd=d;a.g=2}}else 3==a.g&&(b?O6(a,b):0==a.i.length||a.Cd||O6(a))},O6=function(a,b){if(b)if(6<a.Ng){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.rk-1;var d=N6(a)}else c=b.D,d=b.ph;else c=a.rk++,d=N6(a);var e=a.gm.clone();c5(e,"SID",a.l);c5(e,"RID",c);c5(e,"AID",a.ki);G6(a,e);c=new T5(a,a.l,c,a.Qh+1);c.Xg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Cd=c;V5(c,e,d)},G6=function(a,b){if(a.Uc){var c=a.Uc.Mv();
c&&g.Kb(c,function(d,e){c5(b,e,d)})}},N6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Ng&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Ng?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Q6=function(a){a.Rb||a.qf||(a.D=1,a.qf=i6((0,g.y)(a.nz,a),0),a.Jh=0)},S6=function(a){if(a.Rb||a.qf||3<=a.Jh)return!1;
a.D++;a.qf=i6((0,g.y)(a.nz,a),R6(a,a.Jh));a.Jh++;return!0},q6=function(a,b,c){a.Bo=c;
a.Je=b.Cf;a.B||K6(a)},L6=function(a){null!=a.Rg&&(g.w.clearTimeout(a.Rg),a.Rg=null)},R6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Uc&&(c=null);var d=(0,g.y)(a.IM,a);c||(c=new g.Im("//www.google.com/images/cleardot.gif"),d5(c));k6(c.toString(),1E4,d)}else Z5(2);T6(a,b)},T6=function(a,b){a.g=0;
a.Uc&&a.Uc.Lu(b);H6(a);F6(a)},H6=function(a){a.g=0;
a.Je=-1;if(a.Uc)if(0==a.o.length&&0==a.i.length)a.Uc.qp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Uc.qp(b)}},o6=function(a,b,c){var d=g.Qm(c);
if(""!=d.g)b&&g.Km(d,b+"."+d.g),g.Lm(d,d.A);else{var e=window.location;d=iqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.sj&&g.Kb(a.sj,function(f,k){c5(d,k,f)});
c5(d,"VER",a.Ng);G6(a,d);return d},i6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},Z5=function(a){V6.dispatchEvent(new C6(V6,a))},W6=function(){},X6=function(){this.g=[];
this.i=[]},Aqa=function(a,b){this.action=a;
this.params=b||{}},Y6=function(a,b){g.H.call(this);
this.g=new g.K(this.nL,0,this);g.J(this,this.g);this.Xc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},Z6=function(a,b,c){this.I=a;
this.B=b;this.l=new g.Sn;this.i=new Y6(this.pM,this);this.g=null;this.ib=!1;this.A=null;this.G="";this.F=this.o=0;this.D=[];this.J=c||!1},Bqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Bo,sessionId:a.g.l,arrayId:a.g.ki}},$6=function(a,b){a.F=b||0;
a.i.stop();a.g&&(3==a.g.g&&P6(a.g),I6(a.g));a.F=0},a7=function(a){return!!a.g&&3==a.g.g},Cqa=function(a,b){(a.B.loungeIdToken=b)||a.i.stop()},b7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.tf(4,a))||"";b&&(this.port=":"+b);this.domain=g.uf(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},c7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ef(c+b,{})},d7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),oe:g.Qa(a.A,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Up(b,a)},Dqa=function(){var a=e7;
f7();g7.push(a);h7(g7)},i7=function(a,b){f7();
var c=g7,d=Eqa(a,String(b));0==c.length?Fqa(d):(h7(c),(0,g.z)(c,function(e){e(d)}))},f7=function(){g7||(g7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",g7,void 0))},Fqa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},h7=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Eqa=function(a,b){var c=((0,g.D)()-Gqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.O.call(this);
this.D=a;this.g=[]},n7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Hqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Vd)(a.g,function(f){return!!s5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=n7(a,b[d])||c;return c},Iqa=function(a,b){var c=a.g.length;
a.g=(0,g.Vd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},o7=function(a,b,c,d){g.O.call(this);
this.B=a;this.A=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ca=NaN},q7=function(a){m7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;p7(this);this.info("Initializing with "+q5(this.g))},r7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=c7(a.l,"/pairing/get_lounge_token_batch");
d7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.yD,a),(0,g.y)(a.xD,a))}},p7=function(a){var b=o5(B5());
b=(0,g.Vd)(b,function(c){return!c.uuid});
return Hqa(a,b)},s7=function(a,b){qqa((0,g.B)(a.g,n5));
b&&C5()},u7=function(a,b){g.O.call(this);
this.B=b;var c=g.Cs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.B(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.A=a;this.l=this.o=NaN;this.i=null;t7("Initialized with "+g.rm(this.g))},v7=function(a,b,c){var d=c7(a.A,"/pairing/get_screen_availability");
d7(a.A,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},w7=function(a,b){a:if(g5(b)!=g5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.rm(a.g)),a.g=b,a.O("screenChange"));Jqa(a)},x7=function(a){isNaN(a.l)||g.Zo(a.l);
a.l=g.Xo((0,g.y)(a.ws,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},t7=function(a){i7("OnlineScreenService",a)},y7=function(a){var b={};
(0,g.z)(a.B(),function(c){c.token?b[c.token]=c.id:this.Ib("Requesting availability of screen w/o lounge token.")});
return b},Jqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Bs("yt-remote-online-screen-ids",a.join(","),60):u5("yt-remote-online-screen-ids")},z7=function(a){m7.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.o=[];this.A={};Kqa(this)},B7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.A[b]);var k=a.Qd();if(k=(c?t5(k,c):null)||t5(k,b)){k.uuid=b;var l=A7(a,k);v7(a.i,l,function(m){e(m?l:null)})}else c?Lqa(a,c,(0,g.y)(function(m){var n=A7(this,new l5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));v7(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},C7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Lqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Up(c7(a.B,"/pairing/get_lounge_token_batch"),e)},D7=function(a){a.g=a.l.Qd();
var b=a.A,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+q5(a.g))},Kqa=function(a){E7(a);
a.l=new q7(a.B);a.l.subscribe("screenChange",(0,g.y)(a.GD,a));D7(a);a.o=o5(g.Cs("yt-remote-automatic-screen-cache")||[]);E7(a);a.info("Initializing automatic screens: "+q5(a.o));a.i=new u7(a.B,(0,g.y)(a.Qd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.O("onlineScreenChange")},a))},A7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=t5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Bs("yt-remote-automatic-screen-cache",(0,g.B)(a.o,n5)));E7(a);a.A[b.uuid]=b.id;g.Bs("yt-remote-device-id-map",a.A,31536E3);return b},E7=function(a){a.A=g.Cs("yt-remote-device-id-map")||{}},F7=function(a,b,c){g.O.call(this);
this.T=c;this.G=a;this.i=b;this.l=null},G7=function(a,b){i7(a.T,b)},I7=function(a,b){F7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.B=(0,g.y)(this.pN,this);this.A=(0,g.y)(this.QL,this);this.o=g.Xo((0,g.y)(function(){H7(this,null)},this),12E4)},Mqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.rm(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.y)(function(){G7(this,"Failed to send message: getMdxSessionStatus.")},a)):G7(a,"Sending yt message without session: "+g.rm(b))},H7=function(a,b){g.Zo(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Kn,a),d=(0,g.y)(a.Td,a);a.dw(b,c,d,5)}}else a.Td(Error("Waiting for session status timed out."))},J7=function(a,b,c){F7.call(this,a,b,"DialSession");
this.o=this.F=null;this.I="";this.N=c;this.A=null;this.D=g.Ha;this.B=NaN;this.J=(0,g.y)(this.sN,this);this.g=g.Ha},K7=function(a){a.g=a.G.mB(a.I,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ha;
this.Kn(b)},a),(0,g.y)(function(b){this.g=g.Ha;
this.Td(b)},a))},L7=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.A){var c=a.A.currentTime||0;b.v=a.A.videoId;b.t=c}F5()&&(b.env_useStageMdx=1);return g.Cf(b)},M7=function(a,b){F7.call(this,a,b,"ManualSession");
this.g=g.Xo((0,g.y)(this.li,this,null),150)},N7=function(a,b,c,d){g.O.call(this);
this.i=a;this.D=b||"233637DE";this.B=c||"cl";this.F=d||!1;this.g=null;this.A=!1;this.l=[];this.o=(0,g.y)(this.vK,this)},O7=function(a,b){return b?g.Ya(a.l,function(c){return m5(b,c.label)},a):null},P7=function(a){i7("Controller",a)},e7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},Q7=function(a){return a.A||!!a.l.length||!!a.g},R7=function(a,b,c){b!=a.g&&(g.Bi(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.i):a.O("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.mz,a,b)),b.l?a.O("yt-remote-cast2-session-change",b.l):c&&a.g.li(null)):a.O("yt-remote-cast2-session-change",null))},S7=function(a){var b=a.i.lB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&m5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=O7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Qqa=function(a,b,c,d,e,f,k){Nqa()?Oqa(b,e,f,k)&&(U7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?V7(a,c):(window.__onGCastApiAvailable=function(l,m){l?V7(a,c):(W7("Failed to load cast API: "+m),X7(!1),U7(!1),u5("yt-remote-cast-available"),u5("yt-remote-cast-receiver"),Y7(),c(!1))},d?g.jp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?uqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?K5():(L5(),J5(Pqa.map(sqa))))):T7("Cannot initialize because not running Chrome")},Y7=function(){T7("dispose");
var a=Z7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);$7(!1);g.ep(a8);a8.length=0},b8=function(){return!!g.Cs("yt-remote-cast-installed")},c8=function(){var a=g.Cs("yt-remote-cast-receiver");
return a?a.friendlyName:null},d8=function(){T7("clearCurrentReceiver");
u5("yt-remote-cast-receiver")},e8=function(){return b8()?Z7()?Z7().getCastSession():(W7("getCastSelector: Cast is not initialized."),null):(W7("getCastSelector: Cast API is not installed!"),null)},g8=function(){b8()?Z7()?f8()?(T7("Requesting cast selector."),Z7().requestSession()):(T7("Wait for cast API to be ready to request the session."),a8.push(g.dp("yt-remote-cast2-api-ready",g8))):W7("requestCastSelector: Cast is not initialized."):W7("requestCastSelector: Cast API is not installed!")},h8=function(a,
b){f8()?Z7().setConnectedScreenStatus(a,b):W7("setConnectedScreenStatus called before ready.")},Nqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.ow||a},Rqa=function(a,b){Z7().init(a,b)},Oqa=function(a,b,c,d){var e=!1;
Z7()||(a=new N7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Bs("yt-remote-cast-available",f);j5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){T7("onReceiverSelected: "+f.friendlyName);
g.Bs("yt-remote-cast-receiver",f);j5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){T7("onReceiverResumed: "+f.friendlyName);
g.Bs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){T7("onSessionChange: "+p5(f));
f||u5("yt-remote-cast-receiver");j5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
T7("cloudview.createSingleton_: "+e);return e},Z7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},V7=function(a,b){X7(!0);
U7(!1);Rqa(a,function(c){c?($7(!0),g.gp("yt-remote-cast2-api-ready")):(W7("Failed to initialize cast API."),X7(!1),u5("yt-remote-cast-available"),u5("yt-remote-cast-receiver"),Y7());b(c)})},T7=function(a){i7("cloudview",a)},W7=function(a){i7("cloudview",a)},X7=function(a){T7("setCastInstalled_ "+a);
g.Bs("yt-remote-cast-installed",a)},f8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},$7=function(a){T7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},U7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},i8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.B=this.D=0;this.g=null;this.hasNext=this.Ke=!1;this.G=this.F=this.i=this.o=0;this.l=NaN;this.A=!1;this.reset(a)},j8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ke=!1;a.hasNext=!1;a.D=0;a.B=(0,g.D)();a.o=0;a.i=0;a.F=0;a.G=0;a.l=NaN;a.A=!1},k8=function(a){return 1==a.playerState?((0,g.D)()-a.B)/1E3:0},l8=function(a,b){a.D=b;
a.B=(0,g.D)()},m8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.B)/1E3+a.D;
case -1E3:return 0}return a.D},n8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&j8(a)},o8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ke;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.B;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.F;b.loadedTime=a.G;b.liveIngestionTime=a.l;return b},r8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.B=[];this.A=new X6;this.l=this.i=null;this.G=(0,g.y)(this.rI,this);this.D=(0,g.y)(this.vk,this);this.F=(0,g.y)(this.qI,this);this.I=(0,g.y)(this.FI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.qt,this),p8(this))):c=3;0!=c&&(b?this.qt(c):g.Xo((0,g.y)(function(){this.qt(c)},this),0));
var d=e8();d&&q8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},s8=function(a){return new i8(a.o.getPlayerContextData())},p8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.B.push(this.o.subscribe(b,g.Qa(this.sK,b),this))},a)},t8=function(a){(0,g.z)(a.B,function(b){this.o.unsubscribeByKey(b)},a);
a.B.length=0},u8=function(a,b){var c=a.A;
50>c.g.length+c.i.length&&a.A.i.push(b)},w8=function(a,b,c){var d=s8(a);
l8(d,c);-1E3!=d.playerState&&(d.playerState=b);v8(a,d)},x8=function(a,b,c){a.o.sendMessage(b,c)},v8=function(a,b){t8(a);
a.o.setPlayerContextData(o8(b));p8(a)},q8=function(a,b){a.l&&(a.l.removeUpdateListener(a.G),a.l.removeMediaListener(a.D),a.vk(null));
a.l=b;a.l&&(i7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.G),a.l.addMediaListener(a.D),a.l.media.length&&a.vk(a.l.media[0]))},y8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=s8(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;l8(d,a.i.getEstimatedTime());v8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},z8=function(a,b,c){return(0,g.y)(function(d){this.Ib("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ib("Retrying "+b+" using MDx browser channel."),x8(this,b,c))},a)},A8=function(a,b,c){g.O.call(this);
this.A=NaN;this.J=!1;this.F=this.D=this.G=this.I=NaN;this.T=[];this.o=this.B=this.l=this.Oa=this.g=null;this.R=a;this.T.push(g.cr(window,"beforeunload",(0,g.y)(this.rD,this)));this.i=[];this.Oa=new i8;this.N=b.id;this.g=Sqa(this,c);this.g.subscribe("handlerOpened",this.vI,this);this.g.subscribe("handlerClosed",this.sI,this);this.g.subscribe("handlerError",this.tI,this);this.g.subscribe("handlerMessage",this.uI,this);Cqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.Ds()&&g.Bs("yt-remote-session-video-id",d)},this)},B8=function(a){i7("conn",a)},Sqa=function(a,b){return new Z6(c7(a.R,"/bc"),b)},C8=function(a,b){a.O("proxyStateChange",b)},Tqa=function(a){a.A=g.Xo((0,g.y)(function(){B8("Connecting timeout");
this.Nh(1)},a),2E4)},D8=function(a){g.Zo(a.A);
a.A=NaN},E8=function(a){g.Zo(a.I);
a.I=NaN},Uqa=function(a){F8(a);
a.G=g.Xo((0,g.y)(function(){G8(this,"getNowPlaying")},a),2E4)},F8=function(a){g.Zo(a.G);
a.G=NaN},I8=function(a,b){b&&(D8(a),E8(a));
b==(a7(a.g)&&isNaN(a.A))?b&&(C8(a,1),G8(a,"getSubtitlesTrack")):b?(a.bw()&&a.Oa.reset(),C8(a,1),G8(a,"getNowPlaying"),H8(a)):a.Nh(1)},Vqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.O("remotePlayerChange"))},J8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;n8(a.Oa,c,d);a.O("remoteQueueChange")},Wqa=function(a,b){b.params=b.params||{};
J8(a,b);K8(a,b);a.O("autoplayDismissed")},K8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
l8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.G=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.F=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.A=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Uqa(a):F8(a);a.O("remotePlayerChange")},Xqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);l8(a.Oa,isNaN(c)?0:c);a.O("remotePlayerChange")}},Yqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.O("remotePlayerChange")},Zqa=function(a,b){a.B=b.params.videoId;
a.O("nowAutoplaying",parseInt(b.params.timeout,10))},$qa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Ke="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.O("previousNextChange")},H8=function(a){g.Zo(a.F);
a.F=g.Xo((0,g.y)(a.Nh,a,1),864E5)},G8=function(a,b,c){c?B8("Sending: action="+b+", params="+g.rm(c)):B8("Sending: action="+b);
a.g.sendMessage(b,c)},L8=function(a){m7.call(this,"ScreenServiceProxy");
this.Wc=a;this.i=[];this.i.push(this.Wc.$_s("screenChange",(0,g.y)(this.nN,this)));this.i.push(this.Wc.$_s("onlineScreenChange",(0,g.y)(this.XJ,this)))},era=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Po("MDX_CONFIG")||b;oqa();z5();M8||(M8=new b7(b?b.loungeApiHost:void 0),F5()&&(M8.g="/api/loungedev"));N8||(N8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",N8,void 0));ara();var c=O8();if(!c){var d=new z7(M8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=O8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Qqa(a,d,function(m){m?P8()&&h8(P8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){j5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),Q8("Initializing: "+g.rm(b)),R8.push(g.dp("yt-remote-cast2-availability-change",function(){j5("yt-remote-receiver-availability-change")})),R8.push(g.dp("yt-remote-cast2-receiver-selected",function(){S8(null);
j5("yt-remote-auto-connect","cast-selector-receiver")})),R8.push(g.dp("yt-remote-cast2-receiver-resumed",function(){j5("yt-remote-receiver-resumed","cast-selector-receiver")})),R8.push(g.dp("yt-remote-cast2-session-change",bra)),R8.push(g.dp("yt-remote-connection-change",function(m){m?h8(P8(),"YouTube TV"):T8()||(h8(null,null),d8())})),a=U8(),b.isAuto&&(a.id+="#dial"),g.Lp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),Q8(" -- with channel params: "+
g.rm(a)),cra(a),c.start(),P8()||dra())},fra=function(){var a=V8();
b8()&&g.Cs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},V8=function(){var a=O8().Wc.$_gos();
var b=W8();b&&X8()&&(s5(a,b)||a.push(b));return nqa(a)},Y8=function(){var a=gra();
!a&&b8()&&c8()&&(a={key:"cast-selector-receiver",name:c8()});return a},gra=function(){var a=V8(),b=W8();
b||(b=T8());return g.Ya(a,function(c){return b&&m5(b,c.key)?!0:!1})},W8=function(){var a=P8();
if(!a)return null;var b=O8().Qd();return t5(b,a)},bra=function(a){Q8("remote.onCastSessionChange_: "+p5(a));
if(a){var b=W8();b&&b.id==a.id?h8(b.id,"YouTube TV"):(b&&Z8(),$8(a,1))}else X8()&&Z8()},Z8=function(){f8()?Z7().stopSession():W7("stopSession called before API ready.");
var a=X8();a&&(a.disconnect(1),a9(null))},b9=function(){var a=X8();
return!!a&&3!=a.getProxyState()},Q8=function(a){i7("remote",a)},O8=function(){if(!c9){var a=g.x("yt.mdx.remote.screenService_");
c9=a?new L8(a):null}return c9},P8=function(){return g.x("yt.mdx.remote.currentScreenId_")},d9=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},e9=function(){return g.x("yt.mdx.remote.connectData_")},S8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},X8=function(){return g.x("yt.mdx.remote.connection_")},a9=function(a){var b=X8();
S8(null);a||d9("");g.Ga("yt.mdx.remote.connection_",a,void 0);N8&&((0,g.z)(N8,function(c){c(a)}),N8.length=0);
b&&!a?j5("yt-remote-connection-change",!1):!b&&a&&j5("yt-remote-connection-change",!0)},T8=function(){var a=g.Ds();
if(!a)return null;var b=O8().Qd();return t5(b,a)},$8=function(a,b){W8()&&W8();
if(f9)g9=a;else{d9(a.id);var c=new A8(M8,a,U8());c.connect(b,e9());c.subscribe("beforeDisconnect",function(d){j5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){X8()&&a9(null)});
a9(c)}},dra=function(){var a=T8();
a?(Q8("Resume connection to: "+p5(a)),$8(a,0)):(D5(),d8(),Q8("Skipping connecting because no session screen found."))},ara=function(){var a=U8();
if(g.Yb(a)){a=y5();var b=g.Cs("yt-remote-session-name")||"",c=g.Cs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},U8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},cra=function(a){a?(g.Bs("yt-remote-session-app",a.app),g.Bs("yt-remote-session-name",a.name)):(u5("yt-remote-session-app"),u5("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},h9=function(a,b,c){g.H.call(this);
this.A=a;this.i=b;this.l=new g.Or(this);g.J(this,this.l);this.l.L(b,"onCaptionsTrackListChanged",this.sJ);this.l.L(b,"captionschanged",this.pI);this.l.L(b,"captionssettingschanged",this.zA);this.l.L(b,"videoplayerreset",this.Ln);this.l.L(b,"mdxautoplaycancel",this.uC);this.R=this.l.L(b,"onVolumeChange",this.Wy);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.iz,this);c.subscribe("remotePlayerChange",this.xk,this);c.subscribe("remoteQueueChange",this.Ln,this);c.subscribe("autoplayUpNext",this.Ly,
this);c.subscribe("previousNextChange",this.fz,this);c.subscribe("nowAutoplaying",this.bz,this);c.subscribe("autoplayDismissed",this.Ky,this);this.suggestion=null;this.G=new g.NB(64);this.o=new g.K(this.xA,500,this);g.J(this,this.o);this.B=new g.K(this.yA,1E3,this);g.J(this,this.B);this.J=new M5(this.SM,0,this);g.J(this,this.J);this.D={};this.T=new g.K(this.ZA,1E3,this);g.J(this,this.T);this.I=new g.dl(this.NF,1E3,this);g.J(this,this.I);this.N=g.Ha;this.zA();this.Ln();this.xk()},i9=function(a,b){a.A.Mc(b,
a.i.getVideoData().lengthSeconds)},k9=function(a){i9(a,0);
a.o.stop();j9(a,new g.NB(64))},m9=function(a,b){if(l9(a)&&!a.F){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.oA(a.i.getVideoData(1).videoId,c);a.D=s8(a.g).g}},n9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Me,f5(c));j9(a,new g.NB(1))},hra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{PQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.F=!1):(a.i.loadModule("captions"),a.F=!0)}else a.i.setOption("captions","track",{})},l9=function(a){return s8(a.g).videoId==a.i.getVideoData(1).videoId},j9=function(a,b){a.B.stop();
var c=a.G;if(!g.TB(c,b)){var d=g.U(b,2);d!=g.U(a.G,2)&&g.RJ(a.i,d);a.G=b;ira(a.A,c,b)}},o9=function(){g.W.call(this,{C:"div",
H:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{C:"div",H:"ytp-mdx-popup-dialog-inner-content",K:[{C:"div",H:"ytp-mdx-popup-title",U:"You're signed out"},{C:"div",H:"ytp-mdx-popup-description",U:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{C:"div",H:"ytp-mdx-privacy-popup-buttons",K:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Cancel"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
U:"Confirm"}]}]}]});this.l=new g.LP(this,250);g.J(this,this.l);this.D=this.i["ytp-mdx-privacy-popup-cancel"];this.L(this.D,"click",this.o);this.A=this.i["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},p9=function(a){g.W.call(this,{C:"div",
H:"ytp-remote",K:[{C:"div",H:"ytp-remote-display-status",K:[{C:"div",H:"ytp-remote-display-status-icon",K:[g.$O()]},{C:"div",H:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.LP(this,250);g.J(this,this.l);this.o=a;this.L(a,"presentingplayerstatechange",this.A);jra(this,g.NJ(a))},jra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.ZM("Error on $RECEIVER_NAME",c):g.UB(b)||g.U(b,4)?g.ZM("Playing on $RECEIVER_NAME",c):g.ZM("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.uT.call(this,"Play on",0,a,b);
this.l=a;this.D={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},r9=function(a){g.rK.call(this,a);
this.i={key:r5(),name:"This computer"};this.A=null;this.o=[];this.I=this.g=null;this.F=[this.i];this.l=this.i;this.fk=new g.NB(64);this.J=0;this.Om=-1;this.B=null;if(!g.ly(g.X(this.player))){a=this.player;var b=g.GC(a);b&&(b=b.sn())&&(b=new q9(a,b),g.J(this,b));b=new p9(a);g.J(this,b);g.bK(a,b.element,4);this.B=new o9;g.J(this,this.B);g.bK(a,this.B.element,4);this.G=!!T8()}this.D=null},s9=function(a){a.D&&(a.player.removeEventListener("presentingplayerstatechange",a.D),a.D=null)},ira=function(a,b,
c){a.fk=c;
a.player.O("presentingplayerstatechange",new g.XC(c,b))},t9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)Z8();
else{var c;(c=!g.P(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.Po("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.Po("SESSION_INDEX")&&!g.Po("LOGGED_IN")))||a.G||!a.B);c||g.ly(g.X(a.player))||(g.UB(g.NJ(a.player))?a.player.pauseVideo():(a.D=(0,g.y)(a.WL,a),a.player.addEventListener("presentingplayerstatechange",a.D)),a.B&&a.B.l.show(),X8()||(f9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();
if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Me,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=f5(c))&&(d.locationInfo=c);c=d}else c=null;Q8("Connecting to: "+g.rm(b));"cast-selector-receiver"==b.key?(S8(c||null),f8()?Z7().setLaunchParams(c||null):W7("setLaunchParams called before ready.")):!c&&b9()&&P8()==b.key?j5("yt-remote-connection-change",
!0):(Z8(),S8(c||null),c=O8().Qd(),(c=t5(c,b.key))&&$8(c,1))}},f6={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},e6={"'":"\\'"},kra={},lqa={MN:"atp",cQ:"ska",RP:"que",rP:"mus",bQ:"sus",JO:"dsp",YP:"seq"};
k5.prototype.fg=function(){var a=new k5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var E5,x5="",tqa=G5("loadCastFramework")||G5("loadCastApplicationFramework"),Pqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(M5,g.H);g.h=M5.prototype;g.h.nD=function(a){this.o=arguments;this.g=!1;this.Ca?this.l=(0,g.D)()+this.Xc:this.Ca=g.bl(this.A,this.Xc)};
g.h.stop=function(){this.Ca&&(g.w.clearTimeout(this.Ca),this.Ca=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.B.apply(null,this.o)))};
g.h.V=function(){this.stop();M5.bb.V.call(this)};
g.h.oD=function(){this.l?(this.Ca=g.bl(this.A,this.l-(0,g.D)()),this.l=null):(this.Ca=null,this.i?this.g=!0:(this.g=!1,this.B.apply(null,this.o)))};O5.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
O5.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};P5.prototype.g=null;P5.prototype.getOptions=function(){var a;(a=this.g)||(a={},R5(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var u9;g.Sa(Q5,P5);u9=new Q5;g.h=T5.prototype;g.h.Xg=null;g.h.Ae=!1;g.h.Si=null;g.h.mt=null;g.h.Ci=null;g.h.Xh=null;g.h.Xf=null;g.h.Bg=null;g.h.ph=null;g.h.sc=null;g.h.al=0;g.h.Ee=null;g.h.Do=null;g.h.og=null;g.h.Kj=-1;g.h.hA=!0;g.h.Mg=!1;g.h.mq=0;g.h.Un=null;var $5={},Y5={};g.h=T5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.fM=function(a){a=a.target;var b=this.Un;b&&3==w6(a)?b.Gj():this.hB(a)};
g.h.hB=function(a){try{if(a==this.sc)a:{var b=w6(this.sc),c=this.sc.A,d=this.sc.getStatus();if(g.Jd&&!g.ld(10)||g.Ld&&!g.kd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.bg&&!A6(this.sc))break a;this.Mg||4!=b||7==c||(8==c||0>=d?this.g.ze(3):this.g.ze(2));j6(this);var e=this.sc.getStatus();this.Kj=e;var f=A6(this.sc);(this.Ae=200==e)?(4==b&&b6(this),this.A?(d6(this,b,f),g.bg&&this.Ae&&3==b&&(this.ca.ea(this.i,"tick",this.ZL),this.i.start())):a6(this,f),this.Ae&&!this.Mg&&(4==b?this.g.In(this):(this.Ae=
!1,X5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.og=3,Z5(13)):(this.og=0,Z5(14)),b6(this),c6(this))}}catch(k){this.sc&&A6(this.sc)}finally{}};
g.h.ZL=function(){var a=w6(this.sc),b=A6(this.sc);this.al<b.length&&(j6(this),d6(this,a,b),this.Ae&&4!=a&&X5(this))};
g.h.vL=function(a){i6((0,g.y)(this.uL,this,a),0)};
g.h.uL=function(a){this.Mg||(j6(this),a6(this,a),X5(this))};
g.h.pz=function(a){i6((0,g.y)(this.tL,this,a),0)};
g.h.tL=function(a){this.Mg||(b6(this),this.Ae=a,this.g.In(this),this.g.ze(4))};
g.h.cancel=function(){this.Mg=!0;b6(this)};
g.h.FL=function(){this.Si=null;var a=(0,g.D)();0<=a-this.mt?(2!=this.Xh&&this.g.ze(3),b6(this),this.og=2,Z5(18),c6(this)):h6(this,this.mt-a)};
g.h.getLastError=function(){return this.og};g.h=n6.prototype;g.h.kq=null;g.h.Gd=null;g.h.Vn=!1;g.h.nw=null;g.h.dm=null;g.h.Sq=null;g.h.lq=null;g.h.ge=null;g.h.Cf=-1;g.h.Jj=null;g.h.ej=null;g.h.connect=function(a){this.lq=a;a=o6(this.g,null,this.lq);Z5(3);this.nw=(0,g.D)();var b=this.g.F;null!=b?(this.Jj=b[0],(this.ej=b[1])?(this.ge=1,p6(this)):(this.ge=2,r6(this))):(e5(a,"MODE","init"),this.Gd=new T5(this,void 0,void 0,void 0),this.Gd.Xg=this.kq,W5(this.Gd,a,!1,null,!0),this.ge=0)};
g.h.vC=function(a){if(a)this.ge=2,r6(this);else{Z5(4);var b=this.g;b.Je=b.eg.Cf;U6(b,9)}a&&this.ze(2)};
g.h.Fp=function(a){return this.g.Fp(a)};
g.h.abort=function(){this.Gd&&(this.Gd.cancel(),this.Gd=null);this.Cf=-1};
g.h.mw=function(){return!1};
g.h.jz=function(a,b){this.Cf=a.Kj;if(0==this.ge)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.Cf;U6(c,2);return}this.Jj=c[0];this.ej=c[1]}else c=this.g,c.Je=this.Cf,U6(c,2);else if(2==this.ge)if(this.Vn)Z5(7),this.Sq=(0,g.D)();else if("11111"==b){if(Z5(6),this.Vn=!0,this.dm=(0,g.D)(),c=this.dm-this.nw,!g.Jd||g.ld(10)||500>c)this.Cf=200,this.Gd.cancel(),Z5(12),q6(this.g,this,!0)}else Z5(8),this.dm=this.Sq=(0,g.D)(),this.Vn=!1};
g.h.In=function(){this.Cf=this.Gd.Kj;if(this.Gd.Ae)0==this.ge?this.ej?(this.ge=1,p6(this)):(this.ge=2,r6(this)):2==this.ge&&((!g.Jd||g.ld(10)?!this.Vn:200>this.Sq-this.dm)?(Z5(11),q6(this.g,this,!1)):(Z5(12),q6(this.g,this,!0)));else{0==this.ge?Z5(9):2==this.ge&&Z5(10);var a=this.g;this.Gd.getLastError();a.Je=this.Cf;U6(a,2)}};
g.h.Nk=function(){return this.g.Nk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ze=function(a){this.g.ze(a)};g.Sa(s6,g.qk);var yqa=/^https?$/i,lra=["POST","PUT"];g.h=s6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.A=0;this.Z=b;this.R=!1;this.i=!0;this.g=this.N?S5(this.N):S5(u9);this.T=this.N?this.N.getOptions():u9.getOptions();this.g.onreadystatechange=(0,g.y)(this.ow,this);try{i5(x6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){i5(x6(this,"Error opening Xhr: "+f.message));v6(this,f);return}a=c||"";
var e=this.headers.clone();d&&hqa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Pd(),xqa);c=g.w.FormData&&a instanceof g.w.FormData;!g.ab(lra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.S&&(this.g.withCredentials=this.S);try{z6(this),0<this.B&&(this.J=wqa(this.g),i5(x6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.J)),this.J?(this.g.timeout=this.B,this.g.ontimeout=(0,g.y)(this.pw,this)):this.G=g.bl(this.pw,this.B,this)),i5(x6(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){i5(x6(this,"Send error: "+f.message)),v6(this,f)}};
g.h.pw=function(){"undefined"!=typeof g.gY&&this.g&&(this.l="Timed out after "+this.B+"ms, aborting",this.A=8,x6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(x6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),u6(this))};
g.h.V=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),u6(this,!0));s6.bb.V.call(this)};
g.h.ow=function(){this.fa()||(this.aa||this.D||this.o?y6(this):this.uK())};
g.h.uK=function(){y6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<w6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.u(this.l)?this.l:String(this.l)};g.h=B6.prototype;g.h.sj=null;g.h.Cd=null;g.h.Rb=null;g.h.jq=null;g.h.gm=null;g.h.zu=null;g.h.xm=null;g.h.rk=0;g.h.JH=0;g.h.Uc=null;g.h.mg=null;g.h.qf=null;g.h.Rg=null;g.h.eg=null;g.h.Bo=null;g.h.ki=-1;g.h.Xw=-1;g.h.Je=-1;g.h.Qh=0;g.h.Jh=0;g.h.Ng=8;var V6=new g.qk;g.Sa(C6,g.Sj);g.Sa(D6,g.Sj);g.Sa(E6,g.Sj);g.h=B6.prototype;g.h.connect=function(a,b,c,d,e){Z5(0);this.jq=b;this.sj=c||{};d&&g.Da(e)&&(this.sj.OSID=d,this.sj.OAID=e);this.B?(i6((0,g.y)(this.Tu,this,a),100),K6(this)):this.Tu(a)};
g.h.Tu=function(a){this.eg=new n6(this);this.eg.kq=null;this.eg.i=this.A;this.eg.connect(a)};
g.h.mw=function(){return 0==this.g};
g.h.oz=function(a){this.mg=null;P6(this,a)};
g.h.nz=function(){this.qf=null;this.Rb=new T5(this,this.l,"rpc",this.D);this.Rb.Xg=null;this.Rb.mq=0;var a=this.zu.clone();c5(a,"RID","rpc");c5(a,"SID",this.l);c5(a,"CI",this.Bo?"0":"1");c5(a,"AID",this.ki);G6(this,a);if(!g.Jd||g.ld(10))c5(a,"TYPE","xmlhttp"),W5(this.Rb,a,!0,this.xm,!1);else{c5(a,"TYPE","html");var b=this.Rb,c=!!this.xm;b.Xh=3;b.Xf=d5(a.clone());g6(b,c)}};
g.h.jz=function(a,b){if(0!=this.g&&(this.Rb==a||this.Cd==a))if(this.Je=a.Kj,this.Cd==a&&3==this.g)if(7<this.Ng){try{var c=this.A.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Rb)if(this.Rb.Ci+3E3<this.Cd.Ci)L6(this),this.Rb.cancel(),this.Rb=null;else break a;S6(this);Z5(19)}}else this.Xw=c[1],0<this.Xw-this.ki&&37500>c[2]&&this.Bo&&0==this.Jh&&!this.Rg&&(this.Rg=i6((0,g.y)(this.lI,this),6E3));else U6(this,11)}else b!=kra.kO.g&&U6(this,11);else if(this.Rb==a&&
L6(this),!g.wb(b)){c=this.A.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.ki=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.xm=e[2],e=e[3],null!=e?this.Ng=e:this.Ng=6,this.g=3,this.Uc&&this.Uc.Nu(),this.zu=o6(this,this.Nk()?this.xm:null,this.jq),Q6(this)):"stop"==e[0]&&U6(this,7):3==this.g&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Uc&&this.Uc.Mu(e),this.Jh=0)}}};
g.h.lI=function(){null!=this.Rg&&(this.Rg=null,this.Rb.cancel(),this.Rb=null,S6(this),Z5(20))};
g.h.In=function(a){if(this.Rb==a){L6(this);this.Rb=null;var b=2}else if(this.Cd==a)this.Cd=null,b=1;else return;this.Je=a.Kj;if(0!=this.g)if(a.Ae)1==b?(b=(0,g.D)()-a.Ci,V6.dispatchEvent(new D6(V6,a.ph?a.ph.length:0,b,this.Qh)),J6(this),this.o.length=0):Q6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.Cd||this.mg||1==this.g||2<=this.Qh?d=!1:(this.mg=i6((0,g.y)(this.oz,this,a),R6(this,this.Qh)),this.Qh++,d=!0);d=!(d||2==b&&S6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.NC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.IM=function(a){a?Z5(2):(Z5(1),T6(this,8))};
g.h.Fp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new s6;a.S=!1;return a};
g.h.isActive=function(){return!!this.Uc&&this.Uc.isActive(this)};
g.h.ze=function(a){V6.dispatchEvent(new E6(V6,a))};
g.h.Nk=function(){return!(!g.Jd||g.ld(10))};
g.h=W6.prototype;g.h.Nu=function(){};
g.h.Mu=function(){};
g.h.Lu=function(){};
g.h.qp=function(){};
g.h.Mv=function(){return{}};
g.h.isActive=function(){return!0};g.h=X6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Vma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.Ec=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Sa(Y6,g.H);g.h=Y6.prototype;g.h.nL=function(){this.Xc=Math.min(3E5,2*this.Xc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Xc+15E3*Math.random();g.tn(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Xc=5E3};g.Sa(Z6,W6);g.h=Z6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.Yg(a)};
g.h.O=function(a,b){return this.l.O.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.Bi(this.l),$6(this),g.Bi(this.i),this.i=null)};
g.h.fa=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.G="";this.i.stop();this.A=a||null;this.o=b||0;a=this.I+"/test";b=this.I+"/bind";var d=new B6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.Uc=null);d.Uc=this;this.g=d;e?this.g.connect(a,b,this.B,e.l,e.ki):c?this.g.connect(a,b,this.B,c.sessionId,c.arrayId):this.g.connect(a,b,this.B)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):a7(this)&&M6(this.g,c)};
g.h.Nu=function(){this.i.reset();this.A=null;this.o=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)M6(this.g,a[b])}this.O("handlerOpened")};
g.h.Lu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.O("handlerError",a)};
g.h.qp=function(a){if(!this.i.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Mv=function(){var a={v:2};this.G&&(a.gsessionid=this.G);0!=this.o&&(a.ui=""+this.o);0!=this.F&&(a.ui=""+this.F);this.A&&g.fc(a,this.A);return a};
g.h.Mu=function(a){"S"==a[0]?this.G=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),I6(this.g)):this.O("handlerMessage",new Aqa(a[0],a[1]))};
g.h.pM=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.Cd&&b++;0==b&&this.connect(this.A,this.o)};b7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
b7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
b7.prototype.A=function(a){a(Error("request timed out"))};var Gqa=(0,g.D)(),g7=null,k7=Array(50),j7=-1,l7=!1;g.Sa(m7,g.O);m7.prototype.Qd=function(){return this.g};
m7.prototype.contains=function(a){return!!s5(this.g,a)};
m7.prototype.get=function(a){return a?t5(this.g,a):null};
m7.prototype.info=function(a){i7(this.D,a)};g.t(o7,g.O);g.h=o7.prototype;g.h.start=function(){!this.g&&isNaN(this.Ca)&&this.kB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ca)||(g.Zo(this.Ca),this.Ca=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.kB=function(){this.Ca=NaN;this.g=g.Up(c7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.y)(this.lN,this),onError:(0,g.y)(this.kN,this),oe:(0,g.y)(this.mN,this)})};
g.h.lN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.O("pairingComplete",new l5(c))};
g.h.kN=function(a){this.g=null;a.status&&404==a.status?this.i>=mra.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=mra[this.i],this.Ca=g.Xo((0,g.y)(this.kB,this),a),this.i++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.mN=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};
var mra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(q7,m7);g.h=q7.prototype;g.h.start=function(){p7(this)&&this.O("screenChange");!g.Cs("yt-remote-lounge-token-expiration")&&r7(this);g.Zo(this.i);this.i=g.Xo((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){p7(this);n7(this,a);s7(this,!1);this.O("screenChange");b(a);a.token||r7(this)};
g.h.remove=function(a,b){var c=p7(this);Iqa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.xo=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.V=function(){g.Zo(this.i);q7.bb.V.call(this)};
g.h.yD=function(a){p7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&i7(this.D,"Missed "+b+" lounge tokens.")};
g.h.xD=function(a){i7(this.D,"Requesting lounge tokens failed: "+a)};g.t(u7,g.O);g.h=u7.prototype;g.h.start=function(){var a=parseInt(g.Cs("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?x7(this):(this.o=(0,g.D)()+3E5,g.Bs("yt-remote-fast-check-period",this.o),this.ws())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){t7("Updating availability on schedule.");var a=this.B(),b=g.Lb(this.g,function(c,d){return c&&!!t5(a,d)},this);
w7(this,b)};
g.h.V=function(){g.Zo(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.ws=function(){g.Zo(this.l);this.l=NaN;this.i&&this.i.abort();var a=y7(this);if(g5(a)){var b=c7(this.A,"/pairing/get_screen_availability");this.i=d7(this.A,b,{lounge_token:g.Rb(a).join(",")},(0,g.y)(this.QK,this,a),(0,g.y)(this.PK,this))}else w7(this,{}),x7(this)};
g.h.QK=function(a,b){this.i=null;var c=g.Rb(y7(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;w7(this,d);x7(this)}else this.Ib("Changing Screen set during request."),this.ws()};
g.h.PK=function(a){this.Ib("Screen availability failed: "+a);this.i=null;x7(this)};
g.h.Ib=function(a){i7("OnlineScreenService",a)};g.Sa(z7,m7);g.h=z7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.O("screenChange"),this.i.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.xo=function(a,b,c,d){this.l.contains(a)?this.l.xo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.D,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.g:g.fb(this.g,(0,g.Vd)(this.o,function(b){return!this.contains(b)},this))};
g.h.lB=function(){return(0,g.Vd)(this.Qd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.mB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.Bi(f);d(A7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Bi(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.oN=function(a,b,c,d){g.Up(c7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new l5(f.screen||{});if(!k.name||C7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);C7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(A7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
oe:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Bi(this.l);g.Bi(this.i);z7.bb.V.call(this)};
g.h.GD=function(){D7(this);this.O("screenChange");this.i.update()};
z7.prototype.dispose=z7.prototype.dispose;g.Sa(F7,g.O);g.h=F7.prototype;g.h.Kn=function(a){this.l=a;this.O("sessionScreen",this.l)};
g.h.Td=function(a){this.fa()||(a&&G7(this,""+a),this.l=null,this.O("sessionScreen",null))};
g.h.info=function(a){i7(this.T,a)};
g.h.oB=function(){return null};
g.h.Fs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){G7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Fs("");F7.bb.V.call(this)};g.Sa(I7,F7);g.h=I7.prototype;g.h.Es=function(a){if(this.g){if(this.g==a)return;G7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.B);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A)}this.g=a;this.g.addUpdateListener(this.B);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.A);Mqa(this)};
g.h.li=function(a){this.info("launchWithParams no-op for Cast: "+g.rm(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Td()},this),(0,g.y)(function(){this.Td(Error("Failed to stop receiver app."))},this)):this.Td(Error("Stopping cast device witout session."))};
g.h.Fs=g.Ha;g.h.V=function(){this.info("disposeInternal");g.Zo(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.B),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A));this.g=null;I7.bb.V.call(this)};
g.h.QL=function(a,b){if(!this.fa())if(b){var c=N5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.rm(c));switch(d){case "mdxSessionStatus":H7(this,c.screenId);break;default:G7(this,"Unknown youtube message: "+d)}}else G7(this,"Unable to parse message.")}else G7(this,"No data in message.")};
g.h.dw=function(a,b,c,d){B7(this.G,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(G7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Xo((0,g.y)(this.dw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.oB=function(){return this.g};
g.h.pN=function(a){this.fa()||a||(G7(this,"Cast session died."),this.Td())};g.Sa(J7,F7);g.h=J7.prototype;g.h.Es=function(a){this.o=a;this.o.addUpdateListener(this.J)};
g.h.li=function(a){this.A=a;this.D()};
g.h.stop=function(){this.g();this.g=g.Ha;g.Zo(this.B);this.o?this.o.stop((0,g.y)(this.Td,this,null),(0,g.y)(this.Td,this,"Failed to stop DIAL device.")):this.Td()};
g.h.V=function(){this.g();this.g=g.Ha;g.Zo(this.B);this.o&&this.o.removeUpdateListener(this.J);this.o=null;J7.bb.V.call(this)};
g.h.sN=function(a){this.fa()||a||(G7(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Td())};
g.h.Bq=function(a){this.I=r5();if(this.A){var b=new chrome.cast.DialLaunchResponse(!0,L7(this));a(b);K7(this)}else this.D=(0,g.y)(function(){g.Zo(this.B);this.D=g.Ha;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,L7(this));a(c);K7(this)},this),this.B=g.Xo((0,g.y)(function(){this.D()},this),100)};
g.h.bE=function(a,b,c){B7(this.G,this.F.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.Kn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Bq(b,c)},this),(0,g.y)(function(d){G7(this,"Failed to get DIAL screen: "+d);
this.Bq(b,c)},this))};g.Sa(M7,F7);M7.prototype.stop=function(){this.Td()};
M7.prototype.Es=g.Ha;M7.prototype.li=function(){g.Zo(this.g);this.g=NaN;var a=t5(this.G.Qd(),this.i.label);a?this.Kn(a):this.Td(Error("No such screen"))};
M7.prototype.V=function(){g.Zo(this.g);this.g=NaN;M7.bb.V.call(this)};g.Sa(N7,g.O);g.h=N7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.y)(this.zK,this);c=new chrome.cast.ApiConfig(c,(0,g.y)(this.lz,this),f,d,e);c.customDialLaunchCallback=(0,g.y)(this.MI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),Dqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.nB,this)),this.l=S7(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(k){this.Ib("Failed to set initial custom receivers: "+g.rm(k))},this)),this.O("yt-remote-cast2-availability-change",Q7(this)),b(!0))},this),(0,g.y)(function(k){this.Ib("Failed to initialize API: "+g.rm(k));
b(!1)},this))};
g.h.wM=function(a,b){P7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)P7("Unsetting old screen status: "+this.g.i.friendlyName),R7(this,null)}if(a&&b){if(!this.g){c=t5(this.i.Qd(),a);if(!c){P7("setConnectedScreenStatus: Unknown screen.");return}var d=O7(this,c);d||(P7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.y)(function(e){this.Ib("Failed to set initial custom receivers: "+g.rm(e))},this)));
P7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);R7(this,new M7(this.i,d),!0)}this.g.Fs(b)}else P7("setConnectedScreenStatus: no screen.")};
g.h.xM=function(a){this.fa()?this.Ib("Setting connection data on disposed cast v2"):this.g?this.g.li(a):this.Ib("Setting connection data without a session")};
g.h.rN=function(){this.fa()?this.Ib("Stopping session on disposed cast v2"):this.g?(this.g.stop(),R7(this,null)):P7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.lz,this),(0,g.y)(this.WK,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.nB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.x("yt.mdx.remote.debug.handlers_")||[],e7);g.Bi(this.g);N7.bb.V.call(this)};
g.h.Ib=function(a){i7("Controller",a)};
g.h.mz=function(a,b){this.g==a&&(b||R7(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.vK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),P7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)P7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{P7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.O("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:R7(this,
new M7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:R7(this,new J7(this.i,a,this.B));break;case chrome.cast.ReceiverType.CAST:R7(this,new I7(this.i,a));break;default:this.Ib("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Ib("Stopping receiver w/o session: "+a.friendlyName)}else this.Ib("onReceiverAction_ called without receiver.")};
g.h.MI=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ib("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Ib("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return P7("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ib('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);R7(this,new J7(this.i,b,this.B))}b=this.g;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.bE,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Bq,b))};
g.h.lz=function(a){if(!this.fa()){P7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)P7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),R7(this,new I7(this.i,b),!0);else{this.Ib("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=t5(this.i.Qd(),c.label);d&&m5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(P7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Bi(this.g),this.g=new I7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.mz,this,this.g)),this.g.li(null));this.g.Es(a)}}};
g.h.qN=function(){return this.g?this.g.oB():null};
g.h.WK=function(a){this.fa()||(this.Ib("Failed to estabilish a session: "+g.rm(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&R7(this,null))};
g.h.zK=function(a){P7("Receiver availability updated: "+a);if(!this.fa()){var b=Q7(this);this.A=a==chrome.cast.ReceiverAvailability.AVAILABLE;Q7(this)!=b&&this.O("yt-remote-cast2-availability-change",Q7(this))}};
g.h.nB=function(){this.fa()||(this.l=S7(this),P7("Updating custom receivers: "+g.rm(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(){this.Ib("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",Q7(this)))};
N7.prototype.setLaunchParams=N7.prototype.xM;N7.prototype.setConnectedScreenStatus=N7.prototype.wM;N7.prototype.stopSession=N7.prototype.rN;N7.prototype.getCastSession=N7.prototype.qN;N7.prototype.requestSession=N7.prototype.requestSession;N7.prototype.init=N7.prototype.init;N7.prototype.dispose=N7.prototype.dispose;var a8=[];i8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";j8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ke=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.B=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.F=a.duration,this.G=a.loadedTime,this.l=a.liveIngestionTime,this.A=
!isNaN(this.l))};
i8.prototype.isAdPlaying=function(){return 1081==this.playerState};
i8.prototype.getDuration=function(){return this.A?this.F+k8(this):this.F};
i8.prototype.clone=function(){return new i8(o8(this))};g.t(r8,g.O);g.h=r8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,z8(this,"play")):x8(this,"play"),w8(this,1,m8(s8(this))),this.O("remotePlayerChange")):u8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,z8(this,"pause")):x8(this,"pause"),w8(this,2,m8(s8(this))),this.O("remotePlayerChange")):u8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=s8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,z8(this,"seekTo",{newTime:a}))}else x8(this,"seekTo",{newTime:a});w8(this,3,a);this.O("remotePlayerChange")}else u8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,z8(this,"stopVideo")):x8(this,"stopVideo");var a=s8(this);a.index=-1;a.videoId="";j8(a);v8(this,a);this.O("remotePlayerChange")}else u8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=s8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Ib("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Ib("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);x8(this,"setVolume",e)}c.muted=b;c.volume=a;v8(this,c)}else u8(this,g.Qa(this.setVolume,a,b))};
g.h.oA=function(a,b){if(1==this.g){var c=s8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.rm(b.style),g.fc(d,c.g));x8(this,"setSubtitlesTrack",d);v8(this,c)}else u8(this,g.Qa(this.oA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();x8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=s8(this);d.audioTrackId=c;v8(this,d)}else u8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=s8(this);c=c||0;var m={videoId:a,currentIndex:c};n8(l,a,c);g.Da(b)&&(l8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.rm(k));x8(this,"setPlaylist",m);d||v8(this,l)};
g.h.Pn=function(a,b){if(1==this.g){if(a&&b){var c=s8(this);n8(c,a,b);v8(this,c)}x8(this,"previous")}else u8(this,g.Qa(this.Pn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=s8(this);n8(c,a,b);v8(this,c)}x8(this,"next")}else u8(this,g.Qa(this.nextVideo,a,b))};
g.h.ov=function(){1==this.g?x8(this,"dismissAutoplay"):u8(this,this.ov)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){t8(this);this.o=null;this.A.clear();q8(this,null);g.O.prototype.V.call(this)};
g.h.qt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.A.isEmpty();)b=a=this.A,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.sK=function(a,b){this.O(a,b)};
g.h.rI=function(a){if(!a)this.vk(null),q8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=s8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,v8(this,b)}};
g.h.vk=function(a){i7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.F);if(this.i=a)this.i.addUpdateListener(this.F),y8(this),this.O("remotePlayerChange")};
g.h.qI=function(a){a?(y8(this),this.O("remotePlayerChange")):this.vk(null)};
g.h.Vs=function(){x8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.FI=function(){var a=e8();a&&q8(this,a)};
g.h.Ib=function(a){i7("CP",a)};g.t(A8,g.O);g.h=A8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;l8(this.Oa,m);this.o="UNSUPPORTED";B8("Connecting with setPlaylist and params: "+g.rm(l));this.g.connect({method:"setPlaylist",
params:g.rm(l)},a,A5())}else B8("Connecting without params"),this.g.connect({},a,A5());Tqa(this)};
g.h.dispose=function(){this.fa()||(this.O("beforeDispose"),C8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){D8(this);F8(this);E8(this);g.Zo(this.D);this.D=NaN;g.Zo(this.F);this.F=NaN;this.l=null;g.dr(this.T);this.T.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.B=this.i=this.Oa=this.g=null};
g.h.rD=function(){this.Nh(2)};
g.h.vI=function(){B8("Channel opened");this.J&&(this.J=!1,E8(this),this.I=g.Xo((0,g.y)(function(){B8("Timing out waiting for a screen.");this.Nh(1)},this),15E3));
rqa(Bqa(this.g),this.N)};
g.h.sI=function(){B8("Channel closed");isNaN(this.A)?D5(!0):D5();this.dispose()};
g.h.tI=function(a){D5();isNaN(this.Aj())?(B8("Channel error: "+a+" without reconnection"),this.dispose()):(this.J=!0,B8("Channel error: "+a+" with reconnection in "+this.Aj()+" ms"),C8(this,2))};
g.h.uI=function(a){a.params?B8("Received: action="+a.action+", params="+g.rm(a.params)):B8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=N5(a.params.devices);this.i=(0,g.B)(a,function(c){return new k5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
I8(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
I8(this,!1);break;case "remoteConnected":var b=new k5(N5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||eqa(this.i,b);
break;case "remoteDisconnected":b=new k5(N5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":J8(this,a);break;case "nowPlaying":Wqa(this,a);break;case "onStateChange":K8(this,a);break;case "onAdStateChange":Xqa(this,a);break;case "onVolumeChanged":Yqa(this,a);break;case "onSubtitlesTrackChanged":Vqa(this,a);break;case "nowAutoplaying":Zqa(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.O("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.O("autoplayModeChange",this.o);"DISABLED"==this.o&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":$qa(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:B8("Unrecognized action: "+a.action)}};
g.h.mM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&G8(this,"getNowPlaying")}};
g.h.hD=function(){var a=3;this.fa()||(a=0,isNaN(this.Aj())?a7(this.g)&&isNaN(this.A)&&(a=1):a=2);return a};
g.h.Nh=function(a){B8("Disconnecting with "+a);D8(this);this.O("beforeDisconnect",a);1==a&&D5();$6(this.g,a);this.dispose()};
g.h.gD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),n8(a,this.l,a.index));return o8(a)};
g.h.yM=function(a){var b=new i8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Zo(this.D),this.D=g.Xo((0,g.y)(this.mM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&m8(this.Oa)==m8(b)&&g.rm(this.Oa.g)==g.rm(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.O(d)},this)};
g.h.bw=function(){var a=this.g.B.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Aj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.aD=function(){return this.o||"UNSUPPORTED"};
g.h.bD=function(){return this.B||""};
g.h.jN=function(){if(!isNaN(this.Aj())){var a=this.g.i;g.un(a.g);a.start()}};
g.h.tM=function(a,b){G8(this,a,b);H8(this)};
A8.prototype.subscribe=A8.prototype.subscribe;A8.prototype.unsubscribeByKey=A8.prototype.Kf;A8.prototype.getProxyState=A8.prototype.hD;A8.prototype.disconnect=A8.prototype.Nh;A8.prototype.getPlayerContextData=A8.prototype.gD;A8.prototype.setPlayerContextData=A8.prototype.yM;A8.prototype.getOtherConnectedRemoteId=A8.prototype.bw;A8.prototype.getReconnectTimeout=A8.prototype.Aj;A8.prototype.getAutoplayMode=A8.prototype.aD;A8.prototype.getAutoplayVideoId=A8.prototype.bD;A8.prototype.reconnect=A8.prototype.jN;
A8.prototype.sendMessage=A8.prototype.tM;g.t(L8,m7);g.h=L8.prototype;g.h.Qd=function(a){return this.Wc.$_gs(a)};
g.h.contains=function(a){return!!this.Wc.$_c(a)};
g.h.get=function(a){return this.Wc.$_g(a)};
g.h.start=function(){this.Wc.$_st()};
g.h.add=function(a,b,c){this.Wc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Wc.$_r(a,b,c)};
g.h.xo=function(a,b,c,d){this.Wc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Wc.$_ubk(this.i[a]);this.i.length=0;this.Wc=null;m7.prototype.V.call(this)};
g.h.nN=function(){this.O("screenChange")};
g.h.XJ=function(){this.O("onlineScreenChange")};
z7.prototype.$_st=z7.prototype.start;z7.prototype.$_gspc=z7.prototype.oN;z7.prototype.$_gsppc=z7.prototype.mB;z7.prototype.$_c=z7.prototype.contains;z7.prototype.$_g=z7.prototype.get;z7.prototype.$_a=z7.prototype.add;z7.prototype.$_un=z7.prototype.xo;z7.prototype.$_r=z7.prototype.remove;z7.prototype.$_gs=z7.prototype.Qd;z7.prototype.$_gos=z7.prototype.lB;z7.prototype.$_s=z7.prototype.subscribe;z7.prototype.$_ubk=z7.prototype.Kf;var g9=null,f9=!1,M8=null,N8=null,c9=null,R8=[];g.t(h9,g.H);g.h=h9.prototype;
g.h.V=function(){g.H.prototype.V.call(this);this.o.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.iz,this);this.g.unsubscribe("remotePlayerChange",this.xk,this);this.g.unsubscribe("remoteQueueChange",this.Ln,this);this.g.unsubscribe("autoplayUpNext",this.Ly,this);this.g.unsubscribe("previousNextChange",this.fz,this);this.g.unsubscribe("nowAutoplaying",this.bz,this);this.g.unsubscribe("autoplayDismissed",this.Ky,this);this.g=this.A=null};
g.h.Gx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!s8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==s8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Gj(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.pI=function(a){this.J.nD(a)};
g.h.SM=function(a){this.Gx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.zA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||m9(this,a)};
g.h.Wy=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.xk,this);var b=Math.round(a.volume);a=!!a.muted;var c=s8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.T.start();this.g.subscribe("remotePlayerChange",this.xk,this)}};
g.h.sJ=function(){g.Yb(this.D)||hra(this,this.D);this.F=!1};
g.h.iz=function(a,b){this.B.stop();2==b&&this.yA()};
g.h.xk=function(){if(l9(this)){this.o.stop();var a=s8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.A.Om=1;break;case 1082:case 1083:this.A.Om=0;break;default:this.A.Om=-1}switch(a.playerState){case 1081:case 1:j9(this,new g.NB(8));this.xA();break;case 1085:case 3:j9(this,new g.NB(9));break;case 1083:case 0:j9(this,new g.NB(2));this.I.stop();i9(this,this.i.getVideoData().lengthSeconds);break;case 1084:j9(this,new g.NB(4));break;case 2:j9(this,new g.NB(4));i9(this,m8(a));
break;case -1:j9(this,new g.NB(64));break;case -1E3:j9(this,new g.NB(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=s8(this.g).g;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,hra(this,a));a=s8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.T.isActive()||this.ZA()}else k9(this)};
g.h.fz=function(){this.i.O("mdxpreviousnextchange")};
g.h.Ln=function(){l9(this)||k9(this)};
g.h.uC=function(){this.g.ov()};
g.h.Ly=function(a){a&&(a=g.Up("/watch_queue_ajax",{method:"GET",td:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.yL,this)}))&&(this.N=(0,g.y)(a.abort,a))};
g.h.yL=function(a,b){var c=new g.wA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.O("mdxautoplayupnext",c)};
g.h.bz=function(a){isNaN(a)||this.i.O("mdxnowautoplaying",a)};
g.h.Ky=function(){this.i.O("mdxautoplaycanceled")};
g.h.NF=function(a,b){-1==s8(this.g).playerState?n9(this,a):b&&this.g.seekTo(a)};
g.h.ZA=function(){if(l9(this)){var a=s8(this.g);this.l.Qa(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.L(this.i,"onVolumeChange",this.Wy)}};
g.h.xA=function(){this.o.stop();if(!this.g.fa()){var a=s8(this.g);1==a.playerState&&j9(this,new g.NB(8));i9(this,m8(a));this.o.start()}};
g.h.yA=function(){this.B.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.B.start()};g.t(o9,g.W);o9.prototype.o=function(){j5("mdx-privacy-popup-cancel");this.l.hide()};
o9.prototype.B=function(){j5("mdx-privacy-popup-confirm");this.l.hide()};g.t(p9,g.W);p9.prototype.A=function(a){jra(this,a.state)};g.t(q9,g.uT);q9.prototype.J=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.D=g.tb(a,this.B,this),g.wT(this,(0,g.B)(a,this.B)),a=this.l.getOption("remote","currentReceiver"),this.me(this.B(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.B=function(a){return a.key};
q9.prototype.ye=function(a){return"cast-selector-receiver"==a?"Cast...":this.D[a].name};
q9.prototype.Kc=function(a){g.uT.prototype.Kc.call(this,a);this.l.setOption("remote","currentReceiver",this.D[a]);this.o.kb()};g.t(r9,g.rK);g.h=r9.prototype;
g.h.create=function(){era(g.cy(g.X(this.player)));this.o.push(g.dp("yt-remote-before-disconnect",this.mI,this));this.o.push(g.dp("yt-remote-connection-change",this.AK,this));this.o.push(g.dp("yt-remote-receiver-availability-change",this.gz,this));this.o.push(g.dp("yt-remote-auto-connect",this.yK,this));this.o.push(g.dp("yt-remote-receiver-resumed",this.xK,this));this.o.push(g.dp("mdx-privacy-popup-confirm",this.cM,this));this.o.push(g.dp("mdx-privacy-popup-cancel",this.bM,this));this.gz()};
g.h.load=function(){this.player.cancelPlayback();g.rK.prototype.load.call(this);this.A=new h9(this,this.player,this.g);var a=(a=e9())?a.currentTime:0;var b=b9()?new r8(X8(),void 0):null;0==a&&b&&(a=m8(s8(b)));0!=a&&this.Mc(a);ira(this,this.fk,this.fk);g.yX(this.player.app,6)};
g.h.unload=function(){this.player.O("mdxautoplaycanceled");this.l=this.i;g.Ci(this.A,this.g);this.g=this.A=null;g.rK.prototype.unload.call(this);g.yX(this.player.app,5);s9(this)};
g.h.V=function(){g.ep(this.o);g.rK.prototype.V.call(this)};
g.h.Ye=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.A.Gx.apply(this.A,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Om};
g.h.jD=function(){return this.loaded?this.A.suggestion:null};
g.h.Ke=function(){return this.g?s8(this.g).Ke:!1};
g.h.hasNext=function(){return this.g?s8(this.g).hasNext:!1};
g.h.Mc=function(a,b){this.J=a||0;this.player.O("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=s8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.l+k8(a):a.l,isAtLiveHead:1>=(a.A?a.i+k8(a):a.i)-this.getCurrentTime(),loaded:a.G,seekableEnd:a.A?a.i+k8(a):a.i,seekableStart:0<a.o?a.o+
k8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Pn=function(){this.g&&this.g.Pn()};
g.h.mI=function(a){1==a&&(this.I=this.g?s8(this.g):null)};
g.h.AK=function(){var a=b9()?new r8(X8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.I=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Bi(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,m8(a)));this.player.O("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.gz=function(){this.F=[this.i].concat(fra());var a=Y8()||this.i;t9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.WL=function(a){!this.G&&g.ZC(a,8)&&(this.player.pauseVideo(),s9(this))};
g.h.yK=function(){var a=Y8();t9(this,a)};
g.h.xK=function(){this.l=Y8()};
g.h.cM=function(){this.G=!0;s9(this);f9=!1;g9&&$8(g9,1);g9=null};
g.h.bM=function(){this.G=!1;s9(this);t9(this,this.i);this.l=this.i;f9=!1;g9=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?g8():t9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&g8(),!0):!1}};
g.h.Vs=function(){this.g.Vs()};
g.h.Cb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.NU.remote=r9;})(_yt_player);
